# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Restore workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --no-restore
    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: Signed APK
        path: ./CoaLoad.Android/bin/Release/net9.0-android/publish/com.mahdium.coaload-Signed.apk
    - name: Compress Desktop Archive
      run: |
        cd ./CoaLoad.Desktop/bin/Release/net9.0/linux-x64/publish/
        tar -cJf CoaLoad-Desktop-amd64.tar.xz libSkiaSharp.so libHarfBuzzSharp.so CoaLoad-Desktop
    - name: Upload Desktop Archive
      uses: actions/upload-artifact@v3
      with:
        name: Linux 64 Archive
        path: ./CoaLoad.Desktop/bin/Release/net9.0/linux-x64/publish/CoaLoad-Desktop-amd64.tar.xz

